[package]
name = "rc-validator-network"
description = ""
version = "0.1.0"
authors = ["DKLee <xiuerdwy@gmail.com>"]
edition = "2021"
repository = "https://github.com/ZeroDAO/redot"
keywords = ["substrate", "pallet", "macro", "configuration"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.56"
futures = "0.3.21"
tracing = "0.1.37"
log = "0.4"
rand = "0.8"
derive_more = "0.99.17"
anyhow = "1.0.66"
libp2p = { version = "0.50.0", features = ["dns", "metrics", "identify", "kad", "gossipsub", "macros", "mdns", "mplex", "noise", "ping", "tcp",  "tokio", "yamux", "websocket"] }
tokio-stream = { version = "0.1" }
tokio = { version = "1.21.2", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
prometheus-client = "0.18.1"

# Substrate
# sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
# cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }
# cumulus-primitives-core = { default-features = false, git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }