[package]
name = "rc-validator"
description = ""
version = "0.1.0"
authors = ["DKLee <xiuerdwy@gmail.com>"]
edition = "2021"
repository = "https://github.com/ZeroDAO/redot"
keywords = ["substrate", "pallet", "macro", "configuration"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# rand_core = "0.6.4"
log = "0.4"
anyhow = "1.0.66"
# rand = "0.8.4"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
futures = "0.3.21"
serde = { version = "1.0.163" }
serde_json = "1.0.68"

frost-ed25519 = { version = "1.0.0-rc.0", default-features = false }

redot-core-primitives = { path = "../core-primitives", default-features = false }
rc-validator-network = { path = "../rc-validator-network", default-features = false }

# Melodot
melo-das-db = { git = "https://github.com/ZeroDAO/melodot", default-features = false }

# Substrate
cumulus-primitives-core = { default-features = false, git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }

# cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }
# cumulus-primitives-core = { default-features = false, git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }

[dev-dependencies]
serde = { version = "1.0.163" }

[features]
default = ["std"]
std = [
	"melo-das-db/std",
	"codec/std",
	"scale-info/std",
	"serde/std",
	"redot-core-primitives/std",
	# "cumulus-primitives-core/std",
]
